### ISSUE TITLE
Exception thrown on using World#getEntityAt

### ISSUE THREAD

**Issue by rickbau5** [Vrekt/Lunar#6]
Getting the following exception when using getEntityAt if there is no entity at the given location:
```
Exception in thread "AWT-EventQueue-0" java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at me.vrekt.lunar.world.World.getEntityAt(World.java:144)
```
Offending code:
``` Java
public final Entity getEntityAt(int x, int y) {
    return worldEntities.stream().filter(entity -> entity.getX() == x && entity.getY() == y).findAny().get();
}
```
Changing the `get()` to `.orElse(null);` fixes it.

**Comment by Vrekt** [comment]
Forgot about the orElse thing. Before calling this method you would want to ensure there is an entity there by doing World#isEntityAt

**Comment by Vrekt** [comment]
Fixed.
