### ISSUE TITLE
Ray Casting in World

### ISSUE THREAD

**Issue by rickbau5** [Vrekt/Lunar#7]
I'm currently working on ray casting within the context of the world and tiles. Right now just making an attempt at implementing the basics of it and then we can discuss changes needed to get it to work with what is already in place.

General idea would be this:
```java
RayCastResult result = world.raycast(x, y, targetX, targetY); // or raycast(x, y, dirX, dirY, distance)
Tile tile = result.getCollidedTile(); //null if no collision
boolean didCollide = result.didCollide(); // T/F whether there was a collision with a tile.
Location location = result.getCollidedLocation(); // x,y of the collision
```
Collision is based of the `isSolid()` property of tiles.

So far what I'm seeing is we would need some way to translate between world space and screen space, if we wanted to do pixel perfect ray casting (might as well). This would mean the world would need to be aware of the dimensions of the tiles. I'll have a PR for this probably by tomorrow and we can review it.

For reference, I'm adapting ray casting from [this post](https://www.codeproject.com/articles/15604/ray-casting-in-a-2d-tile-based-environment) (without the solidity matrices for tiles).

**Comment by Vrekt** [comment]
My current raycast system is horrible and it takes a few moves within the tile to correctly detect. This would be nice but how long would we raycast for if no distance is given? Since this hangs the game loop maybe make the raycasting without the distance field on a separate thread.

**Comment by rickbau5** [comment]
Ah yeah, so that ray tracing goes tile by tile, but this actually marches by pixel so it's going to be more accurate, and yes have more overhead. 
I have it running now with ray tracing to 80 nearby tiles and every tick and the game runs fine. Typically you would not rely so heavily on ray tracing, more like for firing a projectile, but I'm using it for line of sight for a fog of war type thing.
It may be worth investigating ray tracing on a different thread, but i would worry about the game state not updating quickly enough.

**Comment by rickbau5** [comment]
Also, i think it's sensible to require the user provides a distance, either that or an end point. In game applications, it usually is acceptable.

**Comment by rickbau5** [comment]
Merged.
