### ISSUE TITLE
Adding/Removing entites during game loop

### ISSUE THREAD

**Issue by rickbau5** [Vrekt/Lunar#9]
Adding and removing entities during the game loop causes a `ConcurrentModificationException`. This varies from implementation to implementation, but basically if an entity is being updated and should be removed, the intuition is to call `world.removeEntity(this)`. However, if the entity is being updated from the world loop, say 
``` java
@Override
public void onTick() {
    worldEntities.forEach(Entity::updateEntity);
}
```
the exception is thrown, because you can't remove the entity from a list that is being traversed.

This is fairly common mistake, and it could be useful to provide the user a solution. I'll make a branch and link it here real quick with a potential solution.

**Comment by Vrekt** [comment]
ive merged the world-entities branch, not having much time lately to review and work on things, sorry about that

**Comment by rickbau5** [comment]
no problem!
